server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: pass_local_user
    password: pass_local
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
      schema-locations: classpath:init-schema.sql, classpath:init-data.sql