version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION:-latest}
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}


  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
      SCHEMA_REGISTRY_DEBUG: 'true'

    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  kafka-broker-1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka-broker-1
    hostname: kafka-broker-1
    ports:
      - "19092:19092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:19092" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./volumes/kafka/broker-1:/var/lib/kafka/data"
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  kafka-broker-2:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    ports:
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:29092" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./volumes/kafka/broker-2:/var/lib/kafka/data"
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  kafka-broker-3:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: kafka-broker-3
    hostname: kafka-broker-3
    ports:
      - "39092:39092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:39092" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./volumes/kafka/broker-3:/var/lib/kafka/data"
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  kafka-ui:
    container_name: kafka-ui
    hostname: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8989:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

#  kafka-debezium-connector:
#    image: debezium/connect:${DEBEZIUM_VERSION}
#    ports:
#      - 8083:8083
#    environment:
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: "connect-config"
#      OFFSET_STORAGE_TOPIC: "connect-offsets"
#      STATUS_STORAGE_TOPIC: "connect-status"
#      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
#      LOGGING_LEVEL: "DEBUG"
#      CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
#      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
#      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#    depends_on:
#      - kafka-broker-1
#      - kafka-broker-2
#      - kafka-broker-3
#      - schema-registry
#    volumes:
#      - "/Users/Shared/debezium-connector-schemaregistry-7.2.5:/kafka/connect/debezium-connector-schemaregistry-7.2.5"
#    networks:
#      - ${GLOBAL_NETWORK:-food-ordering-system}

  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list

      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-response --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic restaurant-approval-request --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic restaurant-approval-response --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic customer --delete --if-exists

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-response --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-response --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic customer --replication-factor 3 --partitions 3


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  db:
    image: postgres:${POSTGRES_VERSION:-14.1}
    container_name: db
    hostname: db
    ports:
      - "5432:5432"                     # 호스트와 컨테이너 간의 포트 바인딩
    environment:
      POSTGRES_DB: postgres             # 데이터베이스 이름
      POSTGRES_USER: pass_local_user
      POSTGRES_PASSWORD: pass_local     # 데이터베이스 비밀번호
      TZ: Asia/Seoul                    # 시간대 설정
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data  # 공유 볼륨 경로
      - ./ddl:/docker-entrypoint-initdb.d
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  migration-customer-service:
    build:
      context: ../flyway/customer-service
      dockerfile: Dockerfile
    volumes:
      - ../flyway/customer-service/migration:/flyway/sql
      - ../flyway/customer-service/conf:/flyway/conf
    depends_on:
      - db
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  seed-customer-service:
    build:
      context: ../flyway/customer-service
      dockerfile: Dockerfile
    volumes:
      - ../flyway/customer-service/seed:/flyway/sql
      - ../flyway/customer-service/conf:/flyway/conf
    depends_on:
      - db
      - migration-customer-service
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

  migration-order-service:
    build:
      context: ../flyway/customer-service
      dockerfile: Dockerfile
    volumes:
      - ../flyway/order-service/migration:/flyway/sql
      - ../flyway/order-service/conf:/flyway/conf
    depends_on:
      - db
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

#  seed-order-service:
#    build:
#      context: ../flyway/customer-service
#      dockerfile: Dockerfile
#    volumes:
#      - ../flyway/order-service/seed:/flyway/sql
#      - .../flyway/order-service/conf:/flyway/conf
#    depends_on:
#      - db
#      - migration-order-service
#    networks:
#      - ${GLOBAL_NETWORK:-food-ordering-system}

  migration-payment-service:
    build:
      context: ../flyway/payment-service
      dockerfile: Dockerfile
    volumes:
      - ../flyway/payment-service/migration:/flyway/sql
      - ../flyway/payment-service/conf:/flyway/conf
    depends_on:
      - db
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

#  seed-payment-service:
#    build:
#      context: ../flyway/payment-service
#      dockerfile: Dockerfile
#    volumes:
#      - ../flyway/payment-service/seed:/flyway/sql
#      - ../flyway/payment-service/conf:/flyway/conf
#    depends_on:
#      - db
#      - migration-payment-service
#    networks:
#      - ${GLOBAL_NETWORK:-food-ordering-system}

  migration-restaurant-service:
    build:
      context: ../flyway/customer-service
      dockerfile: Dockerfile
    volumes:
      - ../flyway/restaurant-service/migration:/flyway/sql
      - ../flyway/restaurant-service/conf:/flyway/conf
    depends_on:
      - db
    networks:
      - ${GLOBAL_NETWORK:-food-ordering-system}

#  seed-restaurant-service:
#    build:
#      context: ../flyway/customer-service
#      dockerfile: Dockerfile
#    volumes:
#      - ../flyway/restaurant-service/seed:/flyway/sql
#      - ../flyway/restaurant-service/conf:/flyway/conf
#    depends_on:
#      - db
#      - migration-restaurant-service
#    networks:
#      - ${GLOBAL_NETWORK:-food-ordering-system}

networks:
  food-ordering-system:
    driver: bridge